language: dart
dart:
  - stable
  - dev

dart_task:
  - test: --platform vm
  - dartanalyzer: --fatal-warnings lib
  - dartfmt
  - pub run build_runner test -- -p chrome

cache:
    directories:
        - $HOME/.pub-cache
